### PR TITLE
Avl integration

### PR DESCRIPTION
**Pull request by trifwn**
Adding AVL extended vortex lattice model to ICARUS.

## Project Description:
AVL is a program for the aerodynamic and flight-dynamic analysis of rigid aircraft
of arbitrary configuration. It employs an extended vortex lattice model for
the lifting surfaces, together with a slender-body model for fuselages and nacelles.
General nonlinear flight states can be specified. The flight dynamic analysis
combines a full linearization of the aerodynamic model about any flight state,
together with specified mass properties.

https://web.mit.edu/drela/Public/web/avl/

## Authors:
Mark Drela, drela (AT) mit (DOT) edu
Harold Youngren, guppy (AT) maine (DOT) rr (DOT) com

### CODE REVIEW

**Review by trifwn — COMMENTED** [review]
ok

**Review by TGDellis — COMMENTED** [review]
ok

**Review by trifwn — COMMENTED** [review]
Merge is ok

**Review by TGDellis — APPROVED** [review]
ok

**Pull request merged**
